// Comprehensive list of COS employers that hire teens
// Career page URLs pre-tested for Colorado Springs job listings

export const COS_EMPLOYERS = [
  // ── FAST FOOD ──────────────────────────────────────────────────
  { company: "McDonald's",        url: 'https://careers.mcdonalds.com/search-jobs?keywords=&location=Colorado+Springs%2C+CO&radius=25&locationId=&locationLevel=city' },
  { company: 'Burger King',       url: 'https://careers.bk.com/jobs?location=Colorado+Springs%2C+CO&distance=25' },
  { company: "Wendy's",           url: 'https://jobs.wendys.com/search/jobs?q=&l=Colorado+Springs+CO' },
  { company: 'Taco Bell',         url: 'https://jobs.tacobell.com/search-jobs/Colorado%20Springs' },
  { company: 'KFC',               url: 'https://careers.kfc.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Arby's",            url: 'https://www.arbys.com/careers/?q=Colorado+Springs' },
  { company: 'Sonic Drive-In',    url: 'https://jobs.sonicdrivein.com/search-jobs?keywords=&location=Colorado+Springs%2C+CO&radius=25' },
  { company: 'Dominos Pizza',     url: 'https://jobs.dominos.com/dominos/jobs?location=Colorado+Springs%2C+CO&radius=25' },
  { company: 'Pizza Hut',         url: 'https://jobs.pizzahut.com/search-jobs?location=Colorado+Springs%2C+CO&radius=25' },
  { company: "Papa John's",       url: 'https://jobs.papajohns.com/search-jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Subway',            url: 'https://jobs.subway.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Jimmy John's",      url: 'https://careers.jimmyjohns.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Jersey Mike's",     url: 'https://www.jerseymikes.com/careers' },
  { company: "Five Guys",         url: 'https://jobs.fiveguys.com/search/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Freddy's",          url: 'https://www.freddys.com/careers/?q=Colorado+Springs' },
  { company: "Culver's",          url: 'https://www.culvers.com/careers#jobs' },
  { company: 'Panda Express',     url: 'https://careers.pandarg.com/en_US/careers/JobResults?keyword=&location=Colorado+Springs%2C+CO' },
  { company: 'Wingstop',          url: 'https://jobs.wingstop.com/search/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Popeyes',           url: 'https://www.popeyes.com/careers' },
  { company: 'IHOP',              url: 'https://careers.ihop.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Denny's",           url: 'https://jobs.dennys.com/search-jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Qdoba',             url: 'https://jobs.qdoba.com/search-jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Noodles & Company', url: 'https://careers.noodles.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Panera Bread',      url: 'https://jobs.panerabread.com/search-jobs?location=Colorado+Springs%2C+CO&radius=25' },
  { company: "Raising Cane's",    url: 'https://www.raisingcanes.com/crewmember-positions/?location=Colorado+Springs' },
  { company: 'Shake Shack',       url: 'https://jobs.shackshack.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Chipotle',          url: 'https://jobs.chipotle.com/search/jobs?location=Colorado+Springs%2C+CO&radius=25' },
  { company: 'Starbucks',         url: 'https://jobs.starbucks.com/search/jobs?location=Colorado+Springs%2C+CO&radius=25' },
  { company: "Dunkin'",           url: 'https://careers.dunkinbrands.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Applebees',         url: 'https://applebees.jobs/en/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Buffalo Wild Wings',url: 'https://jobs.arby.com/bww/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Chili's",           url: 'https://brinker.wd5.myworkdayjobs.com/BrinkerCareers?locationCountry=US&jobFamilyGroup=Restaurant+Hourly' },

  // ── RETAIL ─────────────────────────────────────────────────────
  { company: 'Safeway',           url: 'https://albertsons.wd5.myworkdayjobs.com/albertsons_careers?locationCountry=US&q=Colorado+Springs' },
  { company: 'Sprouts',           url: 'https://jobs.sprouts.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Natural Grocers',   url: 'https://www.naturalgrocers.com/careers/?location=Colorado+Springs' },
  { company: 'Hobby Lobby',       url: 'https://careers.hobbylobby.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Michaels",          url: 'https://jobs.michaels.com/en/search-jobs?location=Colorado+Springs%2C+CO&radius=25' },
  { company: 'Home Depot',        url: 'https://careers.homedepot.com/job-search-results/?q=Colorado%20Springs&category=Store+Hourly' },
  { company: "Lowe's",            url: 'https://jobs.lowes.com/search/?q=Colorado+Springs&location=Colorado+Springs%2C+CO' },
  { company: 'Dollar Tree',       url: 'https://careers.dollartree.com/job-search-results/?location=Colorado+Springs%2C+CO' },
  { company: 'Dollar General',    url: 'https://careers.dollargeneral.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Family Dollar',     url: 'https://jobs.familydollar.com/job-search-results/?location=Colorado+Springs%2C+CO' },
  { company: 'Five Below',        url: 'https://careers.fivebelow.com/search-jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Ross Dress for Less',url: 'https://jobs.rossstores.com/search/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'TJ Maxx',           url: 'https://jobs.tjmaxx.com/search/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Marshalls',         url: 'https://jobs.marshalls.com/search/jobs?location=Colorado+Springs%2C+CO' },
  { company: "Burlington",        url: 'https://jobs.burlingtonstores.com/search-jobs?location=Colorado+Springs%2C+CO' },
  { company: "Kohl's",            url: 'https://careers.kohls.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Best Buy',          url: 'https://jobs.bestbuy.com/bby/jobs?q=&location=Colorado+Springs%2C+CO&radius=25' },
  { company: 'PetSmart',          url: 'https://jobs.petsmart.com/search/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Petco',             url: 'https://careers.petco.com/us/en/search-results?keywords=&location=Colorado+Springs%2C+CO' },
  { company: 'Bath & Body Works', url: 'https://careers.bathandbodyworks.com/us/en/search-results?keywords=Colorado+Springs' },
  { company: 'GameStop',          url: 'https://jobs.gamestop.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'AutoZone',          url: 'https://jobs.autozone.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: "O'Reilly Auto",     url: 'https://corporate.oreillyauto.com/on/demandware.store/Sites-CorpSite-Site/default/Careers-Search?q=Colorado+Springs' },
  { company: 'Walgreens',         url: 'https://jobs.walgreens.com/search-jobs?keywords=&location=Colorado+Springs%2C+CO&radius=25' },
  { company: 'CVS',               url: 'https://jobs.cvshealth.com/us/en/search-results?keywords=Colorado+Springs' },
  { company: 'Costco',            url: 'https://www.costco.com/jobs-at-costco.html' },
  { company: "Sam's Club",        url: 'https://careers.walmart.com/results?q=&l=Colorado+Springs%2C+CO&radius=25&jobType=PT&category=Sams+Club' },
  { company: "Old Navy",          url: 'https://gapinc.eightfold.ai/careers?query=old+navy+colorado+springs' },
  { company: "Hot Topic",         url: 'https://www.hottopic.com/careers/' },
  { company: "Spencer's",         url: 'https://www.spencersonline.com/category/careers/pc/2/' },
  { company: 'Zumiez',            url: 'https://www.zumiez.com/zumiezjobs/' },

  // ── ENTERTAINMENT & RECREATION ──────────────────────────────────
  { company: 'AMC Theaters',      url: 'https://careers.amctheatres.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Regal Cinemas',     url: 'https://regmovies.wd1.myworkdayjobs.com/Regal?location=Colorado+Springs' },
  { company: 'Cinemark',          url: 'https://cnmr.cinemark.com/careers/search-jobs?location=Colorado+Springs%2C+CO' },
  { company: 'Sky Zone',          url: 'https://skyzone.wd1.myworkdayjobs.com/SkyZone?location=Colorado+Springs' },
  { company: 'Main Event',        url: 'https://www.mainevent.com/careers' },
  { company: 'Bowlero',           url: 'https://careers.bowlero.com/jobs?location=Colorado+Springs%2C+CO' },
  { company: 'RUSH Ice Center',   url: 'https://rushicecenter.com/employment/' },
  { company: 'Cheyenne Mtn Zoo',  url: 'https://www.cmzoo.org/explore/jobs/' },
  { company: 'US Olympic Museum', url: 'https://www.teamusa.org/About-the-USOPC/Jobs' },

  // ── LOCAL COS ───────────────────────────────────────────────────
  { company: 'Apogee Rocketry',   url: 'https://www.apogeerockets.com/about/employment' },
  { company: 'Garden of the Gods',url: 'https://www.gardenofgods.com/employment/' },
  { company: 'The Broadmoor',     url: 'https://www.broadmoor.com/about-the-broadmoor/careers/' },
  { company: 'Pikes Peak Summit', url: 'https://www.pikes-peak.com/jobs/' },
  { company: 'Cave of the Winds', url: 'https://caveofthewinds.com/employment/' },
  { company: 'Flying W Ranch',    url: 'https://flyingw.com/employment/' },
  { company: 'ProRodeo Hall of Fame', url: 'https://prorodeohalloffame.com/employment/' },
  { company: 'Switchbacks FC',    url: 'https://www.switchbacksfc.com/jobs' },
  { company: 'Colorado College',  url: 'https://employment.coloradocollege.edu/postings/search' },
  { company: 'UCCS',              url: 'https://www.cu.edu/cu-careers?location=uccs&type=student' },
  { company: 'Ivywild School',    url: 'https://ivywild.com/jobs/' },
]
